window.SLIDE_SETTINGS = {
  footerDatePlaceholder: '2026/04/xx',
  reveal: {
    width: 1600,
    height: 900,
    margin: 0.03,
    minScale: 0.2,
    maxScale: 2.0,
    hash: true,
    controls: true,
    progress: true,
    slideNumber: 'c / t',
    transition: 'slide',
    backgroundTransition: 'fade',
    center: false,
  },
  heroLeafEffect: {
    palette: ['#0f9d58', '#35c98a', '#0b6e3d', '#8fe7be'],
    leafCount: 26,
    sizeMin: 9,
    sizeMax: 26,
    speedMin: 0.3,
    speedMax: 1.2,
    driftMin: -0.16,
    driftMax: 0.16,
    wobbleAmpMin: 5,
    wobbleAmpMax: 19,
    wobbleFreqMin: 0.0018,
    wobbleFreqMax: 0.006,
    rotationSpeedMin: -0.025,
    rotationSpeedMax: 0.025,
    alphaMin: 0.18,
    alphaMax: 0.52,
  },
  sections: [
    { key: 'intro',   label: 'はじめに',       from: 1,  to: 6  },
    { key: 'basics',  label: 'AIの基礎',       from: 7,  to: 8  },
    { key: 'model',   label: '推論モデル',      from: 9,  to: 13 },
    { key: 'tools',   label: 'ツール連携',      from: 14, to: 20 },
    { key: 'ui',      label: 'UI',             from: 21, to: 26 },
    { key: 'apply',   label: '業務適用',        from: 27, to: 30 },
    { key: 'future',  label: 'リスク管理',      from: 31, to: 33 },
    { key: 'summary', label: 'まとめ',          from: 34, to: 34 },
  ],
};
