window.SLIDE_SETTINGS = {
  footerDatePlaceholder: '2026/04/xx',
  reveal: {
    width: 1600,
    height: 900,
    margin: 0.03,
    minScale: 0.2,
    maxScale: 2.0,
    hash: true,
    controls: true,
    progress: true,
    slideNumber: 'c / t',
    transition: 'slide',
    backgroundTransition: 'fade',
    center: false,
  },
  heroLeafEffect: {
    palette: ['#0f9d58', '#35c98a', '#0b6e3d', '#8fe7be'],
    leafCount: 26,
    sizeMin: 9,
    sizeMax: 26,
    speedMin: 0.3,
    speedMax: 1.2,
    driftMin: -0.16,
    driftMax: 0.16,
    wobbleAmpMin: 5,
    wobbleAmpMax: 19,
    wobbleFreqMin: 0.0018,
    wobbleFreqMax: 0.006,
    rotationSpeedMin: -0.025,
    rotationSpeedMax: 0.025,
    alphaMin: 0.18,
    alphaMax: 0.52,
  },
};
